# Carre magique

In [1]:
import numpy as np
import magicsquares_ex as mag

In [2]:
def Square_magic(n, dtype = np.uint32):
    res = np.zeros((n,n), dtype = dtype)
    i = 0
    j = n//2
    res[i,j] = 1
    for v in range(2, n**2+1):
        i2 = (i+2)%n
        j2 = (j+1)%n
        if res[i2,j2] != 0:
            print("Il a un bleme: la case est occupe !")
            i = (i+1)%n
            j = j
        else: 
            i = i2
            j = j2
        res[i,j] = v
    
        print(v)
    return res

def multiple_square():
    pass

T = Square_magic(1, dtype = np.uint8)
print(T)

[[1]]


## Script qui verifie si les carres sont bien magique

In [3]:
mag.square3_ok

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [4]:
sum(mag.square3_ok[0,:]) # Fais la somme des entiers de la premiere ligne (0 en python).

15

In [5]:
mag.square3_ok.diagonal() # matrice diagonale

array([8, 5, 2])

In [6]:
mag.square3_ok[:,::-1].diagonal() # matrice inverse

array([6, 5, 4])

In [7]:
mag.squares_dict

{'square3_ok': array([[8, 1, 6],
        [3, 5, 7],
        [4, 9, 2]]),
 'square_no_diag': array([[8, 1, 6],
        [4, 9, 2],
        [3, 5, 7]]),
 'square_no_row': array([[8, 9, 6],
        [3, 5, 7],
        [4, 1, 2]]),
 'square_no_col': array([[8, 1, 6],
        [7, 5, 3],
        [4, 9, 2]]),
 'square3_no_row_diag': array([[8, 5, 6],
        [3, 1, 7],
        [4, 9, 2]]),
 'square5_ok': array([[ 1, 24,  3, 25, 12],
        [16,  7, 21,  6, 15],
        [23, 14, 18,  8,  2],
        [ 5,  9, 10, 22, 19],
        [20, 11, 13,  4, 17]]),
 'albrecht_durer': array([[16,  3,  2, 13],
        [ 5, 10, 11,  8],
        [ 9,  6,  7, 12],
        [ 4, 15, 14,  1]]),
 'josep_maria_subirachs': array([[ 1, 14, 14,  4],
        [11,  7,  6,  9],
        [ 8, 10, 10,  5],
        [13,  2,  3, 15]]),
 'square5_semi_diabolik': array([[17, 24,  1,  8, 15],
        [23,  5,  7, 14, 16],
        [ 4,  6, 13, 20, 22],
        [10, 12, 19, 21,  3],
        [11, 18, 25,  2,  9]]),
 'benjamin_frankli

In [68]:
def magicSum(n):
    sm = (n*(n**2 + 1))//2 # // permet de travailler avec des entiers et non des floats
    return sm

def checkRows(square):
    sm = magicSum(len(square))
    for row in square:
        rowsum = sum(row)
        if rowsum != sm:
            return False
    return True

def checkCol(square):
    sm = magicSum(len(square))
    for j in range(len(square)):
        col = square[:,j]
        colsum = sum(col)
        if colsum != sm:
            return False
    return True

def checkDiag(square):
    sm = magicSum(len(square))
    diag = square.diagonal()
    if sum(diag) != sm:
        return False
    return True

def checkAllNum_couteux(square):
    n = len(square)
    for num in range(1, n**2+1):
        if num not in square:
            return False
    return True

def checkAllNum(square):
    n = len(square)
    n2 = n**2
    checklist = np.full(n2, False)
    for i in range(n):
        for j in range(n):
            num = square[i,j]
            # if not (1 <= num <= n2): Raccourci Python pour num >=1 and num <= n2
            if num < 1 or num > n2:
                return False
            if checklist[num-1]: # doublon
                return False
            checklist[num-1] = True
            print(checklist)
    return True

In [67]:
table = np.full((9), False)
table

array([False, False, False, False, False, False, False, False, False])

In [43]:
diag = mag.square3_ok.diagonal()
print(diag)
print(sum(diag))

[8 5 2]
15


In [33]:
col = mag.square3_ok[:,2]
print(col)

[6 7 2]


In [9]:
magicSum(5)

65

In [46]:
print(checkRows(mag.square3_ok))
print(checkRows(mag.square_no_row))
print(checkRows(mag.square_no_col))
print(checkRows(mag.square_no_diag))

True
False
True
True


In [39]:
print(checkCol(mag.square3_ok))
print(checkCol(mag.square_no_row))
print(checkCol(mag.square_no_col))
print(checkCol(mag.square_no_diag))

True
True
False
True


In [47]:
print(checkDiag(mag.square3_ok))
print(checkDiag(mag.square_no_row))
print(checkDiag(mag.square_no_col))
print(checkDiag(mag.square_no_diag))

True
True
True
False


In [63]:
print(checkRows(mag.josep_maria_subirachs))
print(checkCol(mag.josep_maria_subirachs))
print(checkDiag(mag.josep_maria_subirachs))
print(checkAllNum(mag.josep_maria_subirachs))

False
False
False
False


In [72]:
#checkAllNum(mag.square3_ok)
checkAllNum(mag.josep_maria_subirachs)

[ True False False False False False False False False False False False
 False False False False]
[ True False False False False False False False False False False False
 False  True False False]


False

In [37]:
len(mag.square3_ok)
mag.square3_ok.shape

(3, 3)

In [45]:
for row in mag.square3_ok:
    

<class 'numpy.ndarray'>
[8 1 6]
<class 'numpy.ndarray'>
[3 5 7]
<class 'numpy.ndarray'>
[4 9 2]


In [73]:
sum(mag.square_no_row)

array([15, 15, 15])

In [75]:
print(mag.square5_ok)
2+mag.square5_ok

[[ 1 24  3 25 12]
 [16  7 21  6 15]
 [23 14 18  8  2]
 [ 5  9 10 22 19]
 [20 11 13  4 17]]


array([[ 3, 26,  5, 27, 14],
       [18,  9, 23,  8, 17],
       [25, 16, 20, 10,  4],
       [ 7, 11, 12, 24, 21],
       [22, 13, 15,  6, 19]])

In [76]:
np.sum(mag.square5_ok)

325

In [82]:
mag.square_no_row.sum(axis=0)

array([15, 15, 15])

In [84]:
mag.square5_ok > 20

array([[False,  True, False,  True, False],
       [False, False,  True, False, False],
       [ True, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False]])

In [87]:
def checkCol_numpy(square):
    sm = magicSum(len(square))
    return all(np.sum(square, axis = 0) == sm)

checkCol_numpy(mag.square_no_col)

False